### PR TITLE
Update pom.xml for JUnit 5.11.0

### LINKED ISSUE #57: bump JUnit dependency to 5.11.0
bump JUnit dependency to [5.11.0](https://junit.org/junit5/docs/5.11.0/release-notes/index.html)

### PR DESCRIPTION
**Pull request by harryssuperman**
Update pom.xml for JUnit 5.11.0 and all platform dependencies
fixes #57

### CODE REVIEW

**Comment by bitcoder** [comment]
thanks. should be fine but I'll need to have a look to that release as I still wasnt able to

**Comment by harryssuperman** [comment]
@bitcoder I hope so. Thanks!

**Comment by michael-o** [comment]
I believe this extension suffers from the same problem as in here: https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/pull/54

**Comment by bitcoder** [comment]
> I believe this extension suffers from the same problem as in here: [fabriciorby/maven-surefire-junit5-tree-reporter#54](https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/pull/54)

can you elaborate? what would be a proper fix to it, from your perspective?

**Comment by michael-o** [comment]
> > I believe this extension suffers from the same problem as in here: [fabriciorby/maven-surefire-junit5-tree-reporter#54](https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/pull/54)
> 
> can you elaborate? what would be a proper fix to it, from your perspective?

Have you read the link actually? Upshot if an extention is in the classpath of the Surefire plugin all of its Surefire dependencies must be in provided scope otherwise it will end in dep mismatches.

**Comment by michael-o** [comment]
> > > I believe this extension suffers from the same problem as in here: [fabriciorby/maven-surefire-junit5-tree-reporter#54](https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/pull/54)
> > 
> > 
> > can you elaborate? what would be a proper fix to it, from your perspective?
> 
> Have you read the link actually? Upshot if an extention is in the classpath of the Surefire plugin all of its Surefire dependencies must be in provided scope otherwise it will end in dep mismatches.

Getting back to this. Looking at the POM I believe that all JUnit deps should be in provided scope because otherwise it will mix/override everything provided by Surefire and/or the user. Though, someone needs to verify it with `dependency:tree`.

**Comment by bitcoder** [comment]
> > > > I believe this extension suffers from the same problem as in here: [fabriciorby/maven-surefire-junit5-tree-reporter#54](https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/pull/54)
> > > 
> > > 
> > > can you elaborate? what would be a proper fix to it, from your perspective?
> > 
> > 
> > Have you read the link actually? Upshot if an extention is in the classpath of the Surefire plugin all of its Surefire dependencies must be in provided scope otherwise it will end in dep mismatches.
> 
> Getting back to this. Looking at the POM I believe that all JUnit deps should be in provided scope because otherwise it will mix/override everything provided by Surefire and/or the user. Though, someone needs to verify it with `dependency:tree`.

Thanks for the feedback We can probably open a new ticket for it; I need some help on this topic though

**Pull request merged**
